# coding: utf-8

"""
    Combined FCSM EOS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import fcsm_eos_api_client
from fcsm_eos_api_client.api.mgmt_api import MgmtApi  # noqa: E501
from fcsm_eos_api_client.rest import ApiException


class TestMgmtApi(unittest.TestCase):
    """MgmtApi unit test stubs"""

    def setUp(self):
        self.api = fcsm_eos_api_client.api.mgmt_api.MgmtApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_management_app_instances_app_instance_id_delete(self):
        """Test case for api_v1_management_app_instances_app_instance_id_delete

        Delete an app instance  # noqa: E501
        """
        pass

    def test_api_v1_management_app_instances_app_instance_id_get(self):
        """Test case for api_v1_management_app_instances_app_instance_id_get

        Get an app instance  # noqa: E501
        """
        pass

    def test_api_v1_management_app_instances_app_instance_id_uninstall_put(self):
        """Test case for api_v1_management_app_instances_app_instance_id_uninstall_put

        """
        pass

    def test_api_v1_management_app_instances_get(self):
        """Test case for api_v1_management_app_instances_get

        List apps instances  # noqa: E501
        """
        pass

    def test_api_v1_management_app_instances_post(self):
        """Test case for api_v1_management_app_instances_post

        Create an app instance  # noqa: E501
        """
        pass

    def test_api_v1_management_apps_app_id_get(self):
        """Test case for api_v1_management_apps_app_id_get

        Get app by id  # noqa: E501
        """
        pass

    def test_api_v1_management_apps_get(self):
        """Test case for api_v1_management_apps_get

        List apps  # noqa: E501
        """
        pass

    def test_api_v1_management_details_get(self):
        """Test case for api_v1_management_details_get

        Get vm details  # noqa: E501
        """
        pass

    def test_api_v1_management_get_bootstrap_script_get(self):
        """Test case for api_v1_management_get_bootstrap_script_get

        Get bootstrap script  # noqa: E501
        """
        pass

    def test_api_v1_management_install_app_post(self):
        """Test case for api_v1_management_install_app_post

        Install application  # noqa: E501
        """
        pass

    def test_api_v1_management_is_managed_get(self):
        """Test case for api_v1_management_is_managed_get

        Check if a vm is managed  # noqa: E501
        """
        pass

    def test_api_v1_management_managed_vms_get(self):
        """Test case for api_v1_management_managed_vms_get

        Return list of managed VM ids  # noqa: E501
        """
        pass

    def test_api_v1_management_register_vm_post(self):
        """Test case for api_v1_management_register_vm_post

        """
        pass

    def test_api_v1_management_replace_apps_post(self):
        """Test case for api_v1_management_replace_apps_post

        Upload apps metadata  # noqa: E501
        """
        pass

    def test_api_v1_management_test_connectivity_post(self):
        """Test case for api_v1_management_test_connectivity_post

        Check connection with Vm  # noqa: E501
        """
        pass

    def test_api_v1_management_tools_tool_id_apps_app_name_get(self):
        """Test case for api_v1_management_tools_tool_id_apps_app_name_get

        Get app by name  # noqa: E501
        """
        pass

    def test_api_v1_management_tools_tool_id_tokens_post(self):
        """Test case for api_v1_management_tools_tool_id_tokens_post

        Generate a new token for the given tool  # noqa: E501
        """
        pass

    def test_api_v1_management_tools_tool_id_tokens_token_value_delete(self):
        """Test case for api_v1_management_tools_tool_id_tokens_token_value_delete

        Delete the token  # noqa: E501
        """
        pass

    def test_api_v1_management_uninstall_app_delete(self):
        """Test case for api_v1_management_uninstall_app_delete

        Uninstall application  # noqa: E501
        """
        pass

    def test_api_v1_management_unregister_subscription_vms_delete(self):
        """Test case for api_v1_management_unregister_subscription_vms_delete

        Unregister vms from subscription  # noqa: E501
        """
        pass

    def test_api_v1_management_unregister_vm_delete(self):
        """Test case for api_v1_management_unregister_vm_delete

        Unregister Vm from management tool  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
