# coding: utf-8

"""
    Combined FCSM EOS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import fcsm_eos_api_client
from fcsm_eos_api_client.models.azure_security_group import AzureSecurityGroup  # noqa: E501
from fcsm_eos_api_client.rest import ApiException


class TestAzureSecurityGroup(unittest.TestCase):
    """AzureSecurityGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAzureSecurityGroup(self):
        """Test AzureSecurityGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fcsm_eos_api_client.models.azure_security_group.AzureSecurityGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
