# coding: utf-8

"""
    Combined FCSM EOS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import fcsm_eos_api_client
from fcsm_eos_api_client.api.img_whitelist_api import ImgWhitelistApi  # noqa: E501
from fcsm_eos_api_client.rest import ApiException


class TestImgWhitelistApi(unittest.TestCase):
    """ImgWhitelistApi unit test stubs"""

    def setUp(self):
        self.api = fcsm_eos_api_client.api.img_whitelist_api.ImgWhitelistApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_whitelist_image_os_get(self):
        """Test case for api_v1_whitelist_image_os_get

        Get image type (OS) for a image  # noqa: E501
        """
        pass

    def test_api_v1_whitelist_images_delete(self):
        """Test case for api_v1_whitelist_images_delete

        Delete whitelist  # noqa: E501
        """
        pass

    def test_api_v1_whitelist_images_get(self):
        """Test case for api_v1_whitelist_images_get

        Get images from whitelist  # noqa: E501
        """
        pass

    def test_api_v1_whitelist_images_image_id_delete(self):
        """Test case for api_v1_whitelist_images_image_id_delete

        Remove image from whitelist  # noqa: E501
        """
        pass

    def test_api_v1_whitelist_images_image_id_get(self):
        """Test case for api_v1_whitelist_images_image_id_get

        Get single image  # noqa: E501
        """
        pass

    def test_api_v1_whitelist_images_image_id_patch(self):
        """Test case for api_v1_whitelist_images_image_id_patch

        Update operating system for image  # noqa: E501
        """
        pass

    def test_api_v1_whitelist_images_image_id_put(self):
        """Test case for api_v1_whitelist_images_image_id_put

        Update operating system for image  # noqa: E501
        """
        pass

    def test_api_v1_whitelist_images_post(self):
        """Test case for api_v1_whitelist_images_post

        Add single image to whitelist  # noqa: E501
        """
        pass

    def test_api_v1_whitelist_os_list_get(self):
        """Test case for api_v1_whitelist_os_list_get

        Get os types and distributions as a list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
