# coding: utf-8

"""
    Combined FCSM EOS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import fcsm_eos_api_client
from fcsm_eos_api_client.models.analytics_operating_system import AnalyticsOperatingSystem  # noqa: E501
from fcsm_eos_api_client.rest import ApiException


class TestAnalyticsOperatingSystem(unittest.TestCase):
    """AnalyticsOperatingSystem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalyticsOperatingSystem(self):
        """Test AnalyticsOperatingSystem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fcsm_eos_api_client.models.analytics_operating_system.AnalyticsOperatingSystem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
