# coding: utf-8

"""
    Combined FCSM EOS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import fcsm_eos_api_client
from fcsm_eos_api_client.api.aws_api import AwsApi  # noqa: E501
from fcsm_eos_api_client.rest import ApiException


class TestAwsApi(unittest.TestCase):
    """AwsApi unit test stubs"""

    def setUp(self):
        self.api = fcsm_eos_api_client.api.aws_api.AwsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_aws_service_api_availability_zones_get(self):
        """Test case for aws_service_api_availability_zones_get

        """
        pass

    def test_aws_service_api_flavor_get(self):
        """Test case for aws_service_api_flavor_get

        Get flavor by id  # noqa: E501
        """
        pass

    def test_aws_service_api_flavors_get(self):
        """Test case for aws_service_api_flavors_get

        Lists flavors  # noqa: E501
        """
        pass

    def test_aws_service_api_image_get(self):
        """Test case for aws_service_api_image_get

        Gets image by id  # noqa: E501
        """
        pass

    def test_aws_service_api_interfaces_get(self):
        """Test case for aws_service_api_interfaces_get

        Gets interfaces for specified subscription  # noqa: E501
        """
        pass

    def test_aws_service_api_keypair_delete(self):
        """Test case for aws_service_api_keypair_delete

        Delete keypair by id  # noqa: E501
        """
        pass

    def test_aws_service_api_keypair_generate_post(self):
        """Test case for aws_service_api_keypair_generate_post

        Create a new keypair  # noqa: E501
        """
        pass

    def test_aws_service_api_keypair_get(self):
        """Test case for aws_service_api_keypair_get

        Get keypair by id  # noqa: E501
        """
        pass

    def test_aws_service_api_keypair_import_post(self):
        """Test case for aws_service_api_keypair_import_post

        Import a new public key  # noqa: E501
        """
        pass

    def test_aws_service_api_keypairs_get(self):
        """Test case for aws_service_api_keypairs_get

        Lists keypairs  # noqa: E501
        """
        pass

    def test_aws_service_api_network_subnets_get(self):
        """Test case for aws_service_api_network_subnets_get

        Lists subnets of specified network and subscription  # noqa: E501
        """
        pass

    def test_aws_service_api_networks_get(self):
        """Test case for aws_service_api_networks_get

        Gets list of all networks  # noqa: E501
        """
        pass

    def test_aws_service_api_private_image_get(self):
        """Test case for aws_service_api_private_image_get

        Gets private image by id  # noqa: E501
        """
        pass

    def test_aws_service_api_private_images_get(self):
        """Test case for aws_service_api_private_images_get

        Lists private images  # noqa: E501
        """
        pass

    def test_aws_service_api_public_image_get(self):
        """Test case for aws_service_api_public_image_get

        Gets public image by id  # noqa: E501
        """
        pass

    def test_aws_service_api_public_images_get(self):
        """Test case for aws_service_api_public_images_get

        Lists public images  # noqa: E501
        """
        pass

    def test_aws_service_api_regions_get(self):
        """Test case for aws_service_api_regions_get

        """
        pass

    def test_aws_service_api_security_groups_get(self):
        """Test case for aws_service_api_security_groups_get

        Lists security groups for specified subscription  # noqa: E501
        """
        pass

    def test_aws_service_api_snapshot_delete(self):
        """Test case for aws_service_api_snapshot_delete

        Deletes snapshots  # noqa: E501
        """
        pass

    def test_aws_service_api_snapshots_get(self):
        """Test case for aws_service_api_snapshots_get

        Lists snapshots  # noqa: E501
        """
        pass

    def test_aws_service_api_snapshots_post(self):
        """Test case for aws_service_api_snapshots_post

        Creates a new snapshot  # noqa: E501
        """
        pass

    def test_aws_service_api_validate_subscription_post(self):
        """Test case for aws_service_api_validate_subscription_post

        """
        pass

    def test_aws_service_api_vm_command_put(self):
        """Test case for aws_service_api_vm_command_put

        Excecutes power action on a VM  # noqa: E501
        """
        pass

    def test_aws_service_api_vm_delete(self):
        """Test case for aws_service_api_vm_delete

        Deletes VM by id  # noqa: E501
        """
        pass

    def test_aws_service_api_vm_details_get(self):
        """Test case for aws_service_api_vm_details_get

        Gets VM details  # noqa: E501
        """
        pass

    def test_aws_service_api_vm_get(self):
        """Test case for aws_service_api_vm_get

        Gets vm by id  # noqa: E501
        """
        pass

    def test_aws_service_api_vm_management_get(self):
        """Test case for aws_service_api_vm_management_get

        Gets management status for a VM  # noqa: E501
        """
        pass

    def test_aws_service_api_vm_password_get(self):
        """Test case for aws_service_api_vm_password_get

        """
        pass

    def test_aws_service_api_vm_patch(self):
        """Test case for aws_service_api_vm_patch

        Modify VM properties  # noqa: E501
        """
        pass

    def test_aws_service_api_vm_security_group_delete(self):
        """Test case for aws_service_api_vm_security_group_delete

        Removes Security Group from a specified VM  # noqa: E501
        """
        pass

    def test_aws_service_api_vm_security_group_put(self):
        """Test case for aws_service_api_vm_security_group_put

        Assign Security Group to a specified VM  # noqa: E501
        """
        pass

    def test_aws_service_api_vm_tag_put(self):
        """Test case for aws_service_api_vm_tag_put

        Set tag value for VM  # noqa: E501
        """
        pass

    def test_aws_service_api_vm_workshift_delete(self):
        """Test case for aws_service_api_vm_workshift_delete

        Delete VM Workshift  # noqa: E501
        """
        pass

    def test_aws_service_api_vm_workshift_post(self):
        """Test case for aws_service_api_vm_workshift_post

        Add a workshift to the VM  # noqa: E501
        """
        pass

    def test_aws_service_api_vm_workshift_put(self):
        """Test case for aws_service_api_vm_workshift_put

        Update VM Workshift  # noqa: E501
        """
        pass

    def test_aws_service_api_vms_get(self):
        """Test case for aws_service_api_vms_get

        Gets list of all vms  # noqa: E501
        """
        pass

    def test_aws_service_api_vms_post(self):
        """Test case for aws_service_api_vms_post

        """
        pass

    def test_aws_service_api_volume_attachment_delete(self):
        """Test case for aws_service_api_volume_attachment_delete

        """
        pass

    def test_aws_service_api_volume_attachment_put(self):
        """Test case for aws_service_api_volume_attachment_put

        """
        pass

    def test_aws_service_api_volume_delete(self):
        """Test case for aws_service_api_volume_delete

        Deletes volume by id  # noqa: E501
        """
        pass

    def test_aws_service_api_volume_get(self):
        """Test case for aws_service_api_volume_get

        Gets volume by id  # noqa: E501
        """
        pass

    def test_aws_service_api_volume_patch(self):
        """Test case for aws_service_api_volume_patch

        Modify volume properties  # noqa: E501
        """
        pass

    def test_aws_service_api_volume_types_get(self):
        """Test case for aws_service_api_volume_types_get

        Gets a list of all volume types user can create volume with  # noqa: E501
        """
        pass

    def test_aws_service_api_volumes_get(self):
        """Test case for aws_service_api_volumes_get

        Gets list of all volumes  # noqa: E501
        """
        pass

    def test_aws_service_api_volumes_post(self):
        """Test case for aws_service_api_volumes_post

        Creates a new EBS volume  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
