# coding: utf-8

"""
    Combined FCSM EOS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class AwsCreateSnapshotParams(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'description': 'str',
        'name': 'str',
        'vm_id': 'str'
    }

    attribute_map = {
        'description': 'description',
        'name': 'name',
        'vm_id': 'vmId'
    }

    def __init__(self, description=None, name=None, vm_id=None):  # noqa: E501
        """AwsCreateSnapshotParams - a model defined in OpenAPI"""  # noqa: E501

        self._description = None
        self._name = None
        self._vm_id = None
        self.discriminator = None

        self.description = description
        self.name = name
        self.vm_id = vm_id

    @property
    def description(self):
        """Gets the description of this AwsCreateSnapshotParams.  # noqa: E501


        :return: The description of this AwsCreateSnapshotParams.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this AwsCreateSnapshotParams.


        :param description: The description of this AwsCreateSnapshotParams.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def name(self):
        """Gets the name of this AwsCreateSnapshotParams.  # noqa: E501


        :return: The name of this AwsCreateSnapshotParams.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AwsCreateSnapshotParams.


        :param name: The name of this AwsCreateSnapshotParams.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def vm_id(self):
        """Gets the vm_id of this AwsCreateSnapshotParams.  # noqa: E501


        :return: The vm_id of this AwsCreateSnapshotParams.  # noqa: E501
        :rtype: str
        """
        return self._vm_id

    @vm_id.setter
    def vm_id(self, vm_id):
        """Sets the vm_id of this AwsCreateSnapshotParams.


        :param vm_id: The vm_id of this AwsCreateSnapshotParams.  # noqa: E501
        :type: str
        """
        if vm_id is None:
            raise ValueError("Invalid value for `vm_id`, must not be `None`")  # noqa: E501

        self._vm_id = vm_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AwsCreateSnapshotParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
