# coding: utf-8

"""
    Combined FCSM EOS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ConfigPlatformConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'platform_id': 'str',
        'value': 'bool'
    }

    attribute_map = {
        'platform_id': 'platformId',
        'value': 'value'
    }

    def __init__(self, platform_id=None, value=None):  # noqa: E501
        """ConfigPlatformConfig - a model defined in OpenAPI"""  # noqa: E501

        self._platform_id = None
        self._value = None
        self.discriminator = None

        if platform_id is not None:
            self.platform_id = platform_id
        if value is not None:
            self.value = value

    @property
    def platform_id(self):
        """Gets the platform_id of this ConfigPlatformConfig.  # noqa: E501

        platform id  # noqa: E501

        :return: The platform_id of this ConfigPlatformConfig.  # noqa: E501
        :rtype: str
        """
        return self._platform_id

    @platform_id.setter
    def platform_id(self, platform_id):
        """Sets the platform_id of this ConfigPlatformConfig.

        platform id  # noqa: E501

        :param platform_id: The platform_id of this ConfigPlatformConfig.  # noqa: E501
        :type: str
        """

        self._platform_id = platform_id

    @property
    def value(self):
        """Gets the value of this ConfigPlatformConfig.  # noqa: E501

        Specifies if platform is enabled  # noqa: E501

        :return: The value of this ConfigPlatformConfig.  # noqa: E501
        :rtype: bool
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ConfigPlatformConfig.

        Specifies if platform is enabled  # noqa: E501

        :param value: The value of this ConfigPlatformConfig.  # noqa: E501
        :type: bool
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigPlatformConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
