# coding: utf-8

"""
    Combined FCSM EOS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ConfigManagementTool(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'type': 'str',
        'tool_type_id': 'str',
        'name': 'str',
        'description': 'str',
        'endpoint_url': 'str',
        'username': 'str'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'tool_type_id': 'toolTypeId',
        'name': 'name',
        'description': 'description',
        'endpoint_url': 'endpointUrl',
        'username': 'username'
    }

    def __init__(self, id=None, type=None, tool_type_id=None, name=None, description=None, endpoint_url=None, username=None):  # noqa: E501
        """ConfigManagementTool - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._type = None
        self._tool_type_id = None
        self._name = None
        self._description = None
        self._endpoint_url = None
        self._username = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if type is not None:
            self.type = type
        if tool_type_id is not None:
            self.tool_type_id = tool_type_id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if endpoint_url is not None:
            self.endpoint_url = endpoint_url
        if username is not None:
            self.username = username

    @property
    def id(self):
        """Gets the id of this ConfigManagementTool.  # noqa: E501


        :return: The id of this ConfigManagementTool.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ConfigManagementTool.


        :param id: The id of this ConfigManagementTool.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this ConfigManagementTool.  # noqa: E501


        :return: The type of this ConfigManagementTool.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ConfigManagementTool.


        :param type: The type of this ConfigManagementTool.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def tool_type_id(self):
        """Gets the tool_type_id of this ConfigManagementTool.  # noqa: E501


        :return: The tool_type_id of this ConfigManagementTool.  # noqa: E501
        :rtype: str
        """
        return self._tool_type_id

    @tool_type_id.setter
    def tool_type_id(self, tool_type_id):
        """Sets the tool_type_id of this ConfigManagementTool.


        :param tool_type_id: The tool_type_id of this ConfigManagementTool.  # noqa: E501
        :type: str
        """

        self._tool_type_id = tool_type_id

    @property
    def name(self):
        """Gets the name of this ConfigManagementTool.  # noqa: E501


        :return: The name of this ConfigManagementTool.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConfigManagementTool.


        :param name: The name of this ConfigManagementTool.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this ConfigManagementTool.  # noqa: E501


        :return: The description of this ConfigManagementTool.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ConfigManagementTool.


        :param description: The description of this ConfigManagementTool.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def endpoint_url(self):
        """Gets the endpoint_url of this ConfigManagementTool.  # noqa: E501


        :return: The endpoint_url of this ConfigManagementTool.  # noqa: E501
        :rtype: str
        """
        return self._endpoint_url

    @endpoint_url.setter
    def endpoint_url(self, endpoint_url):
        """Sets the endpoint_url of this ConfigManagementTool.


        :param endpoint_url: The endpoint_url of this ConfigManagementTool.  # noqa: E501
        :type: str
        """

        self._endpoint_url = endpoint_url

    @property
    def username(self):
        """Gets the username of this ConfigManagementTool.  # noqa: E501


        :return: The username of this ConfigManagementTool.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ConfigManagementTool.


        :param username: The username of this ConfigManagementTool.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigManagementTool):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
