# coding: utf-8

"""
    Combined FCSM EOS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ImgWhitelistImageAdd(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'name': 'str',
        'min_disk_in_gb': 'int',
        'max_disk_in_gb': 'int',
        'min_ram_in_mb': 'int',
        'os': 'ImgWhitelistOSDetailsAddUpdate',
        'is_private': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'min_disk_in_gb': 'minDiskInGb',
        'max_disk_in_gb': 'maxDiskInGb',
        'min_ram_in_mb': 'minRamInMb',
        'os': 'os',
        'is_private': 'isPrivate'
    }

    def __init__(self, id=None, name=None, min_disk_in_gb=None, max_disk_in_gb=None, min_ram_in_mb=None, os=None, is_private=None):  # noqa: E501
        """ImgWhitelistImageAdd - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._name = None
        self._min_disk_in_gb = None
        self._max_disk_in_gb = None
        self._min_ram_in_mb = None
        self._os = None
        self._is_private = None
        self.discriminator = None

        self.id = id
        self.name = name
        self.min_disk_in_gb = min_disk_in_gb
        self.max_disk_in_gb = max_disk_in_gb
        self.min_ram_in_mb = min_ram_in_mb
        self.os = os
        self.is_private = is_private

    @property
    def id(self):
        """Gets the id of this ImgWhitelistImageAdd.  # noqa: E501

        Id of an image returned by `/api/v1/*/compute/publicImages` or `/api/v1/*/compute/privateImages` endpoint  # noqa: E501

        :return: The id of this ImgWhitelistImageAdd.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ImgWhitelistImageAdd.

        Id of an image returned by `/api/v1/*/compute/publicImages` or `/api/v1/*/compute/privateImages` endpoint  # noqa: E501

        :param id: The id of this ImgWhitelistImageAdd.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this ImgWhitelistImageAdd.  # noqa: E501


        :return: The name of this ImgWhitelistImageAdd.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ImgWhitelistImageAdd.


        :param name: The name of this ImgWhitelistImageAdd.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def min_disk_in_gb(self):
        """Gets the min_disk_in_gb of this ImgWhitelistImageAdd.  # noqa: E501


        :return: The min_disk_in_gb of this ImgWhitelistImageAdd.  # noqa: E501
        :rtype: int
        """
        return self._min_disk_in_gb

    @min_disk_in_gb.setter
    def min_disk_in_gb(self, min_disk_in_gb):
        """Sets the min_disk_in_gb of this ImgWhitelistImageAdd.


        :param min_disk_in_gb: The min_disk_in_gb of this ImgWhitelistImageAdd.  # noqa: E501
        :type: int
        """
        if min_disk_in_gb is None:
            raise ValueError("Invalid value for `min_disk_in_gb`, must not be `None`")  # noqa: E501

        self._min_disk_in_gb = min_disk_in_gb

    @property
    def max_disk_in_gb(self):
        """Gets the max_disk_in_gb of this ImgWhitelistImageAdd.  # noqa: E501


        :return: The max_disk_in_gb of this ImgWhitelistImageAdd.  # noqa: E501
        :rtype: int
        """
        return self._max_disk_in_gb

    @max_disk_in_gb.setter
    def max_disk_in_gb(self, max_disk_in_gb):
        """Sets the max_disk_in_gb of this ImgWhitelistImageAdd.


        :param max_disk_in_gb: The max_disk_in_gb of this ImgWhitelistImageAdd.  # noqa: E501
        :type: int
        """
        if max_disk_in_gb is None:
            raise ValueError("Invalid value for `max_disk_in_gb`, must not be `None`")  # noqa: E501

        self._max_disk_in_gb = max_disk_in_gb

    @property
    def min_ram_in_mb(self):
        """Gets the min_ram_in_mb of this ImgWhitelistImageAdd.  # noqa: E501


        :return: The min_ram_in_mb of this ImgWhitelistImageAdd.  # noqa: E501
        :rtype: int
        """
        return self._min_ram_in_mb

    @min_ram_in_mb.setter
    def min_ram_in_mb(self, min_ram_in_mb):
        """Sets the min_ram_in_mb of this ImgWhitelistImageAdd.


        :param min_ram_in_mb: The min_ram_in_mb of this ImgWhitelistImageAdd.  # noqa: E501
        :type: int
        """
        if min_ram_in_mb is None:
            raise ValueError("Invalid value for `min_ram_in_mb`, must not be `None`")  # noqa: E501

        self._min_ram_in_mb = min_ram_in_mb

    @property
    def os(self):
        """Gets the os of this ImgWhitelistImageAdd.  # noqa: E501


        :return: The os of this ImgWhitelistImageAdd.  # noqa: E501
        :rtype: ImgWhitelistOSDetailsAddUpdate
        """
        return self._os

    @os.setter
    def os(self, os):
        """Sets the os of this ImgWhitelistImageAdd.


        :param os: The os of this ImgWhitelistImageAdd.  # noqa: E501
        :type: ImgWhitelistOSDetailsAddUpdate
        """
        if os is None:
            raise ValueError("Invalid value for `os`, must not be `None`")  # noqa: E501

        self._os = os

    @property
    def is_private(self):
        """Gets the is_private of this ImgWhitelistImageAdd.  # noqa: E501

        This field describes if images is a private or public one  # noqa: E501

        :return: The is_private of this ImgWhitelistImageAdd.  # noqa: E501
        :rtype: bool
        """
        return self._is_private

    @is_private.setter
    def is_private(self, is_private):
        """Sets the is_private of this ImgWhitelistImageAdd.

        This field describes if images is a private or public one  # noqa: E501

        :param is_private: The is_private of this ImgWhitelistImageAdd.  # noqa: E501
        :type: bool
        """
        if is_private is None:
            raise ValueError("Invalid value for `is_private`, must not be `None`")  # noqa: E501

        self._is_private = is_private

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImgWhitelistImageAdd):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
