# coding: utf-8

"""
    Combined FCSM EOS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class UserPasswordReset(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'email': 'str',
        'new_password': 'str',
        'token': 'str'
    }

    attribute_map = {
        'email': 'email',
        'new_password': 'newPassword',
        'token': 'token'
    }

    def __init__(self, email=None, new_password=None, token=None):  # noqa: E501
        """UserPasswordReset - a model defined in OpenAPI"""  # noqa: E501

        self._email = None
        self._new_password = None
        self._token = None
        self.discriminator = None

        self.email = email
        self.new_password = new_password
        self.token = token

    @property
    def email(self):
        """Gets the email of this UserPasswordReset.  # noqa: E501


        :return: The email of this UserPasswordReset.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserPasswordReset.


        :param email: The email of this UserPasswordReset.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def new_password(self):
        """Gets the new_password of this UserPasswordReset.  # noqa: E501


        :return: The new_password of this UserPasswordReset.  # noqa: E501
        :rtype: str
        """
        return self._new_password

    @new_password.setter
    def new_password(self, new_password):
        """Sets the new_password of this UserPasswordReset.


        :param new_password: The new_password of this UserPasswordReset.  # noqa: E501
        :type: str
        """
        if new_password is None:
            raise ValueError("Invalid value for `new_password`, must not be `None`")  # noqa: E501
        if new_password is not None and len(new_password) > 72:
            raise ValueError("Invalid value for `new_password`, length must be less than or equal to `72`")  # noqa: E501
        if new_password is not None and len(new_password) < 12:
            raise ValueError("Invalid value for `new_password`, length must be greater than or equal to `12`")  # noqa: E501

        self._new_password = new_password

    @property
    def token(self):
        """Gets the token of this UserPasswordReset.  # noqa: E501


        :return: The token of this UserPasswordReset.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this UserPasswordReset.


        :param token: The token of this UserPasswordReset.  # noqa: E501
        :type: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserPasswordReset):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
