# coding: utf-8

"""
    Combined FCSM EOS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class VmwareSubscription(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'authentication_url': 'str',
        'password': 'str',
        'region_id': 'str',
        'username': 'str'
    }

    attribute_map = {
        'authentication_url': 'authenticationUrl',
        'password': 'password',
        'region_id': 'regionId',
        'username': 'username'
    }

    def __init__(self, authentication_url=None, password=None, region_id=None, username=None):  # noqa: E501
        """VmwareSubscription - a model defined in OpenAPI"""  # noqa: E501

        self._authentication_url = None
        self._password = None
        self._region_id = None
        self._username = None
        self.discriminator = None

        self.authentication_url = authentication_url
        self.password = password
        self.region_id = region_id
        self.username = username

    @property
    def authentication_url(self):
        """Gets the authentication_url of this VmwareSubscription.  # noqa: E501


        :return: The authentication_url of this VmwareSubscription.  # noqa: E501
        :rtype: str
        """
        return self._authentication_url

    @authentication_url.setter
    def authentication_url(self, authentication_url):
        """Sets the authentication_url of this VmwareSubscription.


        :param authentication_url: The authentication_url of this VmwareSubscription.  # noqa: E501
        :type: str
        """
        if authentication_url is None:
            raise ValueError("Invalid value for `authentication_url`, must not be `None`")  # noqa: E501

        self._authentication_url = authentication_url

    @property
    def password(self):
        """Gets the password of this VmwareSubscription.  # noqa: E501


        :return: The password of this VmwareSubscription.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this VmwareSubscription.


        :param password: The password of this VmwareSubscription.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def region_id(self):
        """Gets the region_id of this VmwareSubscription.  # noqa: E501


        :return: The region_id of this VmwareSubscription.  # noqa: E501
        :rtype: str
        """
        return self._region_id

    @region_id.setter
    def region_id(self, region_id):
        """Sets the region_id of this VmwareSubscription.


        :param region_id: The region_id of this VmwareSubscription.  # noqa: E501
        :type: str
        """
        if region_id is None:
            raise ValueError("Invalid value for `region_id`, must not be `None`")  # noqa: E501

        self._region_id = region_id

    @property
    def username(self):
        """Gets the username of this VmwareSubscription.  # noqa: E501


        :return: The username of this VmwareSubscription.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this VmwareSubscription.


        :param username: The username of this VmwareSubscription.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VmwareSubscription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
